vendors:
  image: node:0.10
  working_dir: /mnt
  command: npm install --unsafe-perm
  volumes:
    - .:/mnt
  env_file: .env

proxy:
  image: nginx:1.7
  ports:
    - '7777:7777'
  volumes:
    - devops/proxy:/etc/nginx/conf.d
    - www:/var/www
